management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: compose

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/